// @merge-here entities/base/Actor
// @merge-here entities/base/Paintable
// @merge-here entities/base/Pickable
// @merge-here entities/Billboard
// @merge-here entities/Blueprint
// @merge-here entities/Cable
// @merge-here entities/Canvas
// @merge-here entities/Character
// @merge-here entities/Database
// @merge-here entities/Decal
// @merge-here entities/File
// @merge-here entities/Grenade
// @merge-here entities/Light
// @merge-here entities/Melee
// @merge-here entities/Particle
// @merge-here entities/Player
// @merge-here entities/Prop
// @merge-here entities/SceneCapture
// @merge-here entities/Sound
// @merge-here entities/StaticMesh
// @merge-here entities/TextRender
// @merge-here entities/Trigger
// @merge-here entities/Vehicle
// @merge-here entities/Weapon
// @merge-here entities/WebUI

// @merge-here static/Assets
// @merge-here static/Client
// @merge-here static/Events
// @merge-here static/HTTP
// @merge-here static/Input
// @merge-here static/Package
// @merge-here static/Server
// @merge-here static/Timer
// @merge-here static/World

// @merge-here utils/Color
// @merge-here utils/NanosMath
// @merge-here utils/NanosUtils
// @merge-here utils/Quat
// @merge-here utils/Rotator
// @merge-here utils/Vector
// @merge-here utils/Vector2D
// @merge-here Enums
// @merge-here Console
// @merge-here EventCallback
